# Generated by Django 5.2.4 on 2026-01-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarybase',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
