# Generated by Django 5.2.4 on 2026-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_militarybase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorutility',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
