# Generated by Django 5.2.4 on 2026-01-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_vendorutility_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google Places'), ('yelp', 'Yelp Fusion')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable this API provider')),
                ('api_key_name', models.CharField(help_text='Key name in .keys file (e.g., GOOGLE_PLACES_API_KEY)', max_length=100)),
                ('daily_quota', models.PositiveIntegerField(default=10000, help_text='Maximum API calls per day')),
                ('requests_today', models.PositiveIntegerField(default=0, help_text='API calls made today')),
                ('quota_reset_date', models.DateField(auto_now_add=True, help_text='Date when requests_today resets')),
                ('last_full_sync', models.DateTimeField(blank=True, help_text='Last time a full sync was performed', null=True)),
                ('venues_per_city', models.PositiveIntegerField(default=20, help_text='Top N venues to fetch per city during discovery')),
            ],
            options={
                'verbose_name': 'Venue API Configuration',
                'verbose_name_plural': 'Venue API Configurations',
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('google', 'Google Places'), ('yelp', 'Yelp Fusion')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='enrichment_status',
            field=models.CharField(choices=[('none', 'Not Enriched'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('manual_review', 'Needs Review')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='google_place_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='hours_json',
            field=models.JSONField(blank=True, help_text='Opening hours from API', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='photos_json',
            field=models.JSONField(blank=True, help_text='Photo references from API', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Price level 1-4 ($ to $$$$)', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average rating (e.g., 4.5)', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of reviews/ratings', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='yelp_business_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
