# Generated by Django 5.2.4 on 2026-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_venue_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('trends', 'X Trends'), ('headlines', 'Local Headlines')], max_length=20)),
                ('content_json', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pulse Content',
                'verbose_name_plural': 'Pulse Content',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['content_type', 'is_active'], name='guide_pulse_content_687192_idx')],
            },
        ),
    ]
