# Generated by Django 5.2.4 on 2026-01-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_pulse_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('military', 'Military Base'), ('beach', 'Beach'), ('airport', 'Airport'), ('hospital', 'Hospital'), ('university', 'University')], db_index=True, max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Drive Destination',
                'verbose_name_plural': 'Drive Destinations',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
