# Generated by Django 5.2.4 on 2026-01-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="Model identifier for API calls (e.g., 'gpt-4o', 'claude-sonnet-4-20250514')", max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name for admin display', max_length=150)),
                ('capabilities', models.JSONField(default=list, help_text='List of capabilities: text, vision, image_gen, embedding, code, web_search')),
                ('input_price_per_1k', models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1K input tokens (USD)', max_digits=10, null=True)),
                ('output_price_per_1k', models.DecimalField(blank=True, decimal_places=6, help_text='Price per 1K output tokens (USD)', max_digits=10, null=True)),
                ('price_per_image', models.DecimalField(blank=True, decimal_places=6, help_text='Price per image (for image generation models)', max_digits=10, null=True)),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum output tokens for this model')),
                ('context_window', models.IntegerField(blank=True, help_text='Maximum context window size', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use')),
                ('is_deprecated', models.BooleanField(default=False, help_text='Mark as deprecated (warn on use)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal identifier (e.g., 'openai', 'anthropic')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('xai', 'xAI'), ('blackforestlabs', 'Black Forest Labs'), ('google', 'Google AI')], help_text='Provider type for SDK selection', max_length=50)),
                ('api_key_env_var', models.CharField(blank=True, default='', help_text='Environment variable name for API key (e.g., OPENAI_API_KEY)', max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='Custom API base URL (leave blank for default)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is available for use')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AIOperationConfig',
            fields=[
                ('operation', models.CharField(choices=[('content_venue_description', 'Content: Venue Description'), ('content_city_description', 'Content: City Description'), ('content_refresh', 'Content: Refresh/Update'), ('research_events', 'Research: Event Discovery'), ('research_happenings', 'Research: Local Happenings'), ('research_fact_check', 'Research: Fact Checking'), ('search_venues', 'Search: Venue Recommendations'), ('general_assistant', 'General: Assistant')], help_text='The AI operation to configure', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('temperature', models.FloatField(blank=True, help_text='Override temperature (0.0-2.0). Leave blank for model default.', null=True)),
                ('max_tokens', models.IntegerField(blank=True, help_text='Override max tokens. Leave blank for model default.', null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this operation is enabled')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_model', models.ForeignKey(blank=True, help_text='Fallback model if primary fails', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for', to='ai_services.aimodel')),
                ('model', models.ForeignKey(help_text='Model to use for this operation', on_delete=django.db.models.deletion.PROTECT, related_name='operation_configs', to='ai_services.aimodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Operation Config',
                'verbose_name_plural': 'AI Operation Configs',
                'ordering': ['operation'],
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_services.aiprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('provider', 'model_id')},
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('content_venue_description', 'Content: Venue Description'), ('content_city_description', 'Content: City Description'), ('content_refresh', 'Content: Refresh/Update'), ('research_events', 'Research: Event Discovery'), ('research_happenings', 'Research: Local Happenings'), ('research_fact_check', 'Research: Fact Checking'), ('search_venues', 'Search: Venue Recommendations'), ('general_assistant', 'General: Assistant'), ('other', 'Other')], db_index=True, max_length=50)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('xai', 'xAI'), ('blackforestlabs', 'Black Forest Labs'), ('google', 'Google')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, help_text='Calculated cost in USD', max_digits=10)),
                ('response_time_ms', models.IntegerField(help_text='API response time in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (venue_id, city_id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', 'created_at'], name='ai_services_task_ty_754ec7_idx'), models.Index(fields=['user', 'created_at'], name='ai_services_user_id_ad1a92_idx')],
            },
        ),
    ]
